### ISSUE TITLE
[ Documentation request ] Tracking missing code samples

### ISSUE THREAD

**Issue by rachfop** [temporalio/documentation#1483]
Close this ticket when all issues have been resolved.

# Foundations

- [x] https://github.com/temporalio/documentation/issues/1430
- [x] https://github.com/temporalio/documentation/issues/1431
- [x] https://github.com/temporalio/documentation/issues/1432
- [x] https://github.com/temporalio/documentation/issues/1433
- [x] https://github.com/temporalio/documentation/issues/1434
- [x] https://github.com/temporalio/documentation/issues/1435
- [x] https://github.com/temporalio/documentation/issues/1436
- [x] https://github.com/temporalio/documentation/issues/1437
- [x] https://github.com/temporalio/documentation/issues/1438 
- [x] https://github.com/temporalio/documentation/issues/1439

# Features

- [x] https://github.com/temporalio/documentation/issues/1440
- [x] https://github.com/temporalio/documentation/issues/1441
- [x] https://github.com/temporalio/documentation/issues/1442
- [x] https://github.com/temporalio/documentation/issues/1443
- [x] https://github.com/temporalio/documentation/issues/1444
- [x] https://github.com/temporalio/documentation/issues/1445
- [x] https://github.com/temporalio/documentation/issues/1446
- [x] https://github.com/temporalio/documentation/issues/1447
- [x] https://github.com/temporalio/documentation/issues/1448
- [x] https://github.com/temporalio/documentation/issues/1449
- [x] https://github.com/temporalio/documentation/issues/1450
- [x] https://github.com/temporalio/documentation/issues/1451
- [x] https://github.com/temporalio/documentation/issues/1452
- [x] https://github.com/temporalio/documentation/issues/1453
- [x] https://github.com/temporalio/documentation/issues/1454
- [ ] https://github.com/temporalio/documentation/issues/1455
- [x] https://github.com/temporalio/documentation/issues/1456
- [x] https://github.com/temporalio/documentation/issues/1457
- [x] https://github.com/temporalio/documentation/issues/1458
- [x] https://github.com/temporalio/documentation/issues/1459
- [x] https://github.com/temporalio/documentation/issues/1460
- [ ] https://github.com/temporalio/documentation/issues/1461
- [x] https://github.com/temporalio/documentation/issues/1462
- [x] https://github.com/temporalio/documentation/issues/1463

# Observability

- [x] https://github.com/temporalio/documentation/issues/1464
- [x] https://github.com/temporalio/documentation/issues/1465
- [ ] https://github.com/temporalio/documentation/issues/1466
- [x] https://github.com/temporalio/documentation/issues/1467
- [x] https://github.com/temporalio/documentation/issues/1468
- [x] https://github.com/temporalio/documentation/issues/1469
- [x] https://github.com/temporalio/documentation/issues/1471
- [ ] https://github.com/temporalio/documentation/issues/1472
- [ ] https://github.com/temporalio/documentation/issues/1475
- [ ] https://github.com/temporalio/documentation/issues/1476
- [x] https://github.com/temporalio/documentation/issues/1477
- [ ] https://github.com/temporalio/documentation/issues/1478
- [x] https://github.com/temporalio/documentation/issues/1479
- [x] https://github.com/temporalio/documentation/issues/1480
- [x] https://github.com/temporalio/documentation/issues/1481
- [ ] https://github.com/temporalio/documentation/issues/1482

**Comment by cretz** [comment]
All Python tasks have been completed but I am leaving the issues open just in case you want to comment or request more info. Let me know if you'd rather me close them.

**Comment by bergundy** [comment]
I think we got all the samples here, can we close this @rachfop?

**Comment by flossypurse** [comment]
Opening back up so we can track until publication.

**Comment by flossypurse** [comment]
So, we reached about 84% -
I think we can mark this as complete for now, and utilize our quality improvement sessions as a way to identify and tackle the rest of the gaps.
Since we have added so much more content and sections, there are now other places to look at as well.
